In [ ]:
import xlrd
import openpyxl
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import warnings
import string
import os
warnings.filterwarnings('ignore')

In [ ]:
gu_ko=['서울시 평균','강남구', '강동구', '강북구', '강서구', '관악구', '광진구', '구로구', 
       '금천구', '노원구', '도봉구', '동대문구', '동작구', '마포구', '서대문구', 
       '서초구', '성동구', '성북구', '송파구', '양천구', '영등포구', '용산구', 
       '은평구', '종로구', '중구', '중랑구']

In [ ]:
year = input("원하는 년도 입력: ")
path_dir = "data/미세먼지데이터/미세먼지_" + year +"/"
file_list = os.listdir(path_dir)
length = len(file_list)

for i in range(0, length):
    globals()["pm10_{}".format(i+1)] = pd.read_csv(path_dir+year+"_"+str(i+1)+".csv", encoding='cp949') #csv로 다시 읽기

원하는 년도 입력: 2020

In [ ]:
for i in range(1, length+1):
    for j in range(31, 1, -1):
        if globals()["pm10_{}".format(i)]["{}일".format(j)].isnull().sum() == len(globals()['pm10_{}'.format(i)]):
            globals()["pm10_{}".format(i)].drop(["{}일".format(j)], axis=1, inplace=True)
        else:
            break

In [ ]:
pm10_1

,구분,1일,2일,3일,4일,5일,6일,7일,8일,9일,...,22일,23일,24일,25일,26일,27일,28일,29일,30일,31일
0,서울시 평균,34.0,58.0,69.0,56.0,52.0,39.0,8.0,21.0,50.0,...,45.0,60.0,71.0,51.0,27.0,10.0,12.0,17.0,18.0,25.0
1,강남구,31.0,57.0,61.0,53.0,45.0,36.0,6.0,14.0,46.0,...,44.0,57.0,68.0,44.0,24.0,11.0,12.0,17.0,17.0,26.0
2,강동구,37.0,67.0,84.0,63.0,57.0,42.0,6.0,27.0,55.0,...,54.0,66.0,78.0,47.0,26.0,11.0,13.0,17.0,18.0,31.0
3,강북구,41.0,62.0,65.0,55.0,57.0,38.0,10.0,25.0,53.0,...,45.0,70.0,76.0,54.0,25.0,13.0,15.0,18.0,17.0,32.0
4,강서구,39.0,69.0,89.0,70.0,65.0,46.0,11.0,32.0,59.0,...,54.0,75.0,84.0,64.0,39.0,10.0,14.0,22.0,27.0,43.0
5,관악구,35.0,53.0,71.0,55.0,53.0,41.0,9.0,31.0,50.0,...,45.0,63.0,72.0,49.0,31.0,13.0,14.0,18.0,19.0,18.0
6,광진구,33.0,61.0,74.0,54.0,47.0,33.0,5.0,27.0,44.0,...,42.0,59.0,71.0,42.0,20.0,9.0,10.0,15.0,13.0,27.0
7,구로구,32.0,57.0,73.0,64.0,51.0,37.0,9.0,8.0,49.0,...,45.0,35.0,63.0,47.0,27.0,7.0,9.0,16.0,14.0,20.0
8,금천구,20.0,54.0,64.0,47.0,45.0,33.0,6.0,31.0,53.0,...,45.0,61.0,74.0,55.0,31.0,12.0,13.0,17.0,21.0,25.0
9,노원구,28.0,48.0,54.0,49.0,47.0,44.0,14.0,6.0,49.0,...,40.0,38.0,63.0,51.0,23.0,8.0,9.0,14.0,16.0,24.0
10,도봉구,31.0,54.0,56.0,50.0,51.0,36.0,7.0,3.0,42.0,...,41.0,62.0,61.0,44.0,26.0,6.0,9.0,13.0,13.0,23.0
11,동대문구,33.0,47.0,59.0,51.0,49.0,38.0,11.0,25.0,47.0,...,40.0,60.0,65.0,44.0,24.0,10.0,12.0,17.0,17.0,25.0
12,동작구,39.0,57.0,87.0,67.0,64.0,54.0,12.0,36.0,61.0,...,58.0,60.0,84.0,58.0,34.0,14.0,15.0,20.0,22.0,20.0
13,마포구,31.0,53.0,70.0,54.0,50.0,33.0,7.0,4.0,48.0,...,41.0,60.0,69.0,55.0,29.0,11.0,13.0,19.0,21.0,18.0
14,서대문구,34.0,62.0,67.0,53.0,52.0,27.0,3.0,26.0,48.0,...,40.0,60.0,72.0,60.0,23.0,7.0,8.0,14.0,15.0,13.0
15,서초구,39.0,70.0,78.0,61.0,60.0,43.0,6.0,37.0,50.0,...,50.0,71.0,81.0,55.0,29.0,8.0,11.0,9.0,17.0,16.0
16,성동구,33.0,53.0,62.0,54.0,46.0,35.0,12.0,27.0,48.0,...,42.0,60.0,69.0,45.0,24.0,11.0,13.0,17.0,17.0,27.0
17,성북구,33.0,60.0,66.0,51.0,51.0,39.0,12.0,25.0,44.0,...,45.0,63.0,62.0,43.0,25.0,14.0,15.0,18.0,20.0,25.0
18,송파구,32.0,57.0,62.0,55.0,47.0,40.0,7.0,11.0,51.0,...,43.0,58.0,68.0,43.0,24.0,12.0,13.0,18.0,19.0,28.0
19,양천구,40.0,69.0,90.0,67.0,60.0,46.0,9.0,10.0,56.0,...,51.0,71.0,81.0,62.0,38.0,13.0,16.0,22.0,19.0,29.0
20,영등포구,33.0,55.0,68.0,55.0,51.0,39.0,9.0,25.0,46.0,...,44.0,60.0,66.0,50.0,30.0,12.0,16.0,20.0,22.0,19.0
21,용산구,29.0,54.0,62.0,52.0,44.0,33.0,4.0,23.0,48.0,...,45.0,62.0,71.0,66.0,24.0,10.0,11.0,16.0,16.0,29.0
22,은평구,33.0,58.0,61.0,51.0,50.0,28.0,4.0,3.0,48.0,...,38.0,57.0,69.0,50.0,23.0,8.0,10.0,14.0,15.0,31.0
23,종로구,35.0,49.0,66.0,55.0,54.0,39.0,10.0,29.0,53.0,...,43.0,63.0,72.0,49.0,26.0,11.0,13.0,16.0,17.0,27.0
24,중구,35.0,59.0,65.0,53.0,52.0,42.0,10.0,10.0,51.0,...,42.0,59.0,71.0,46.0,24.0,10.0,12.0,15.0,15.0,26.0
25,중랑구,32.0,60.0,64.0,56.0,51.0,47.0,9.0,27.0,50.0,...,43.0,59.0,69.0,43.0,22.0,11.0,16.0,16.0,16.0,27.0
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
for i in range(1, length+1):
    globals()["pm10_{}".format(i)]=globals()["pm10_{}".format(i)].transpose()
    globals()["pm10_{}".format(i)]=globals()["pm10_{}".format(i)].rename(columns=globals()["pm10_{}".format(i)].iloc[0])
    globals()["pm10_{}".format(i)]=globals()["pm10_{}".format(i)] = globals()["pm10_{}".format(i)]=globals()["pm10_{}".format(i)].drop(globals()["pm10_{}".format(i)].index[0])
    globals()["pm10_{}".format(i)].reset_index(drop=True, inplace=True)

In [ ]:
for i in range(1, length+1):
    globals()["pm10_{}".format(i)]['년'] = year
    globals()["pm10_{}".format(i)]['월'] = i
    globals()["pm10_{}".format(i)]['일'] = range(1, len(globals()["pm10_{}".format(i)])+1)

In [ ]:

pm10 = pd.DataFrame(columns=['년','월','일','미세먼지','자치구'])

In [ ]:
for i in range(1, length+1):
    average=globals()["pm10_{}".format(i)]['서울시 평균'].to_list()
    for j in range(0, len(gu_ko)):
        temp = globals()["pm10_{}".format(i)][['년','월','일',gu_ko[j]]]
        temp = temp.rename(columns={gu_ko[j]: "미세먼지"})
        temp['미세먼지'].fillna(value=pd.Series(average), inplace=True) #결측치 서울시 평균으로 채우기
        temp['자치구'] = gu_ko[j]
        
        pm10 = pm10.append(temp)
        del temp
    
pm10.reset_index(drop=True, inplace=True)
pm10

         년   월   일  미세먼지     자치구
0     2020   1   1  34.0  서울시 평균
1     2020   1   2  58.0  서울시 평균
2     2020   1   3  69.0  서울시 평균
3     2020   1   4  56.0  서울시 평균
4     2020   1   5  52.0  서울시 평균
...    ...  ..  ..   ...     ...
9511  2020  12  27  63.0     중랑구
9512  2020  12  28  66.0     중랑구
9513  2020  12  29  62.0     중랑구
9514  2020  12  30  31.0     중랑구
9515  2020  12  31  24.0     중랑구

[9516 rows x 5 columns]

In [ ]:

degree = pd.DataFrame(columns=['등급'])

In [ ]:
pm10 = pm10.append(degree) 
o_len = len(pm10)

for i in range(0, o_len):
    if pm10['미세먼지'][i] >= 0 and pm10['미세먼지'][i] <= 30:
        pm10['등급'][i] = '좋음'
    elif pm10['미세먼지'][i] >= 30 and pm10['미세먼지'][i] <= 80:
        pm10['등급'][i] = '보통'
    elif pm10['미세먼지'][i] >= 80 and pm10['미세먼지'][i] <= 150:
        pm10['등급'][i] = '나쁨'
    elif pm10['미세먼지'][i] >= 150:
        pm10['등급'][i] = '매우나쁨'

In [ ]:
pm10.drop(['미세먼지'], axis=1, inplace=True)
pm10.rename(columns={'등급': '미세먼지'}, inplace=True)

In [ ]:
pm10.to_csv("data/미세먼지데이터/미세먼지/"+year+"_미세먼지"+".csv", encoding='cp949', index=False) # csv로 저장